Create req.txt
EresDevOrg/ubiquibot-issues pull request #11
Opened 2024-07-22 20:33 UTC by EresDev

Resolves #10

2024-07-22 20:36 UTC, web4er commented
Need to document a private key too

2024-07-22 20:37 UTC, web4er commented
I am starting a new repository for a new project.

2024-07-23 09:32 UTC, EresDev commented
### things to know
- the PR introduces a new file
- the new fils will contain one or more keys to be used for development
- all keys should not contain funds

2024-07-23 09:59 UTC, web4er commented on req.txt
> +request for key
You should add one working key.

2024-07-23 10:00 UTC, EresDev commented on req.txt
> +request for key
Ok, I will add some in a separate PR.

2024-07-23 10:02 UTC, web4er requested changes
An automated script to generate key would help

2024-07-23 10:03 UTC, merged