Update process.issue.test.ts
EresDevOrg/ubiquibot-issues pull request #16
Opened 2024-08-12 21:15 UTC by EresDev

Resolves #15

2024-08-12 21:16 UTC, web4er requested changes
The PR does not address all the goals.

2024-08-12 21:20 UTC, web4er commented on tests/process.issue.test.ts
> +    expect(logSpy).toHaveBeenCalledWith(JSON.stringify(userCommentResults, undefined, 2));
I'm not sure if it's a good idea to rely on logs for testing, is not possible to use output from the processor?

2024-08-12 21:20 UTC, web4er commented on tests/process.issue.test.ts
> +  // parse the issue url
The comment is redundant.

2024-08-12 21:20 UTC, web4er commented on tests/process.issue.test.ts
> +    await activity.init();
```suggestion
    await activity.init();
```
Initialize only one time.

2024-08-12 21:22 UTC, web4er commented on tests/process.issue.test.ts
> +    expect(logSpy).toHaveBeenCalledWith(JSON.stringify(dataPurgeResults, undefined, 2));
```suggestion
    expect(logSpy).toHaveBeenCalledWith(JSON.stringify(dataPurgeResults));
```

2024-08-13 08:55 UTC, web4er commented on tests/process.issue.test.ts
How to test the live url?

2024-08-13 08:56 UTC, EresDev commented on tests/process.issue.test.ts
> +    await activity.init();
resolved.

2024-08-13 08:57 UTC, EresDev commented on tests/process.issue.test.ts
> +    expect(logSpy).toHaveBeenCalledWith(JSON.stringify(userCommentResults, undefined, 2));
By definition dump was just outputting results to stdout, but I could make it return the result as well. Since the console log is what we want to make sure works properly to be reused by other workflows, I thought it would make sense to test it that way because potentially if we forget other logs somewhere that would mess up the output for the next Action step.

2024-08-13 09:03 UTC, merged